# action.yml
name: 'Auto Release EKS'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  
  label_check:
    description: "the label of issue which need to check"
    required: true
  time_check:
    description: ''
    required: true
  uri_notice:
    description: "the webhook_uri which corresponding to robot"
    required: true
  label_skip:
    description: "this action will skip check the issue which labeled label_skip"
    required: false
    default: ""
  time_skip:
    description: "this time will skip check the issue which labeled label_skip"
    required: false
    default: ""
  notice_type:
    description: "the type of message which need to send to robot"
    required: false
    default: "markdown"
  mentions:
    description: "mention list"
    required: false
  corresponding:
    description: 'the corresponding for github login to wecom'
    required: true
  cor_milestone:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token_action }}