# action.yml
name: 'Auto Release EKS'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  notice_key:
    description: "the webhook_uri which corresponding to robot"
    required: true
  corresponding:
    description: 'the corresponding for github login to wecom'
    required: true
  cor_milestone:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'guguchecken/issue_bot:issue_status'
  args:
    - ${{ inputs.token_action }}
    - ${{ inputs.repos }}
    - ${{ inputs.notice_key }}
    - ${{ inputs.corresponding }}
    - ${{ inputs.cor_milestone }}