# action.yml
name: 'Auto Add Assignee'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  assignees:
    description: ""
    required: true
runs:
  using: 'node16'
  main: 'src/index.js'