# action.yml
name: 'Auto Release EKS'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  sender_email:
    description: ''
    required: true
  token_email:
    description: ''
    required: true
  cor_milestones:
    description: ''
    required: true
  number_project:
    description: ''
    required: true
  db_user:
    description: ''
    required: true
  db_passwd:
    description: ''
    required: true
  db_endpoint:
    description: ''
    required: true
  db_database:
    description: ''
    required: true
runs:
  using: 'docker'
  image: 'docker://guguchecken/issue_bot:issue-status-pre-v0.0.1'
  args:
    - ${{ inputs.token_action }}
    - ${{ inputs.repos }}
    - ${{ inputs.cor_milestones }}
    - ${{ inputs.sender_email }}
    - ${{ inputs.token_email }}
    - ${{ inputs.number_project }}
    - ${{ inputs.db_user }}
    - ${{ inputs.db_passwd }}
    - ${{ inputs.db_endpoint }}
    - ${{ inputs.db_database }}
