# action.yml
name: 'Auto Release EKS'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  corresponding:
    description: 'the corresponding for github login to wecom'
    required: true
  sender_email:
    description: ''
    required: false
  token_email:
    description: ''
    required: false
  receiver_emails:
    description: ''
    required: false
  body_message:
    description: ''
    required: false
  cor_milestones:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'docker://guguchecken/issue_bot:issue_status'
  args:
    - ${{ inputs.token_action }}
    - ${{ inputs.repos }}
    - ${{ inputs.corresponding }}
    - ${{ inputs.cor_milestones }}
    - ${{ inputs.sender_email }}
    - ${{ inputs.token_email }}
    - ${{ inputs.receiver_emails }}
    - ${{ input.body_message }}
