# action.yml
name: 'Issue Bot Action'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  labels_check:
    description: 'the corresponding for github login to wecom'
    required: true
  labels_skip:
    description: 'the corresponding for github login to wecom'
    required: true
  time_check:
    description: 'the corresponding for github login to wecom'
    required: true
  notice_key:
    description: 'the corresponding for github login to wecom'
    required: true
  status:
    description: 'the corresponding for github login to wecom'
    required: true
  mentions:
    description: 'the corresponding for github login to wecom'
    required: true
  number_project:
    description: 'the corresponding for github login to wecom'
    required: true
  token_email:
    description: ''
    required: false
  sender_email:
    description: ''
    required: false
  receiver_emails:
    description: ''
    required: false
  hit_max:
    description: ''
    required: false
  db_user:
    description: ''
    required: true
  db_passwd:
    description: ''
    required: true
  db_endpoint:
    description: ''
    required: true
  db_database:
    description: ''
    required: true
runs:
  using: 'docker'
  image: 'docker://guguchecken/issue_bot:issue-time-v0.0.2'
  args:
    - ${{ inputs.token_action }}
    - ${{ inputs.repos }}
    - ${{ inputs.labels_check }}
    - ${{ inputs.labels_skip }}
    - ${{ inputs.time_check }}
    - ${{ inputs.notice_key }}
    - ${{ inputs.status }}
    - ${{ inputs.mentions }}
    - ${{ inputs.number_project }}
    - ${{ inputs.token_email }}
    - ${{ inputs.sender_email }}
    - ${{ inputs.receiver_emails }}
    - ${{ inputs.hit_max }}
    - ${{ inputs.db_user }}
    - ${{ inputs.db_passwd }}
    - ${{ inputs.db_endpoint }}
    - ${{ inputs.db_database }}
