# action.yml
name: 'Issue Bot Action'
description: 'Clearing namespace automatically after ns or the corresponding issue expires'
inputs:
  token_action:  
    description: 'The github access token'
    required: true
  repos:
    description: "the repo"
    required: true
  corresponding:
    description: 'the corresponding for github login to wecom'
    required: true
  label_check:
    description: 'the corresponding for github login to wecom'
    required: true
  time_check:
    description: 'the corresponding for github login to wecom'
    required: true
  notice_key:
    description: 'the corresponding for github login to wecom'
    required: true
  status:
    description: 'the corresponding for github login to wecom'
    required: true
runs:
  using: 'docker'
  image: 'docker://guguchecken/issue_bot:issue_time'
  args:
    - ${{ inputs.token_action }}
    - ${{ inputs.repos }}
    - ${{ inputs.corresponding }}
    - ${{ inputs.label_check }}
    - ${{ inputs.time_check }}
    - ${{ inputs.notice_key }}
    - ${{ inputs.status }}
